Repository UNDP-Data/sdg-labelling-app, pull requests merged in 2023-06, with the labels that each got.

#13 Release v0.4.0
  app.py
  requirements.txt
  src/callbacks.py
  src/communication.py
  src/files/announcements.yml
  src/files/faq.md
  src/ui/__init__.py
  src/ui/accordions.py
  src/ui/affixes.py
  src/ui/alerts.py
  src/ui/alets.py
  src/ui/buttons.py
  src/ui/drawer.py
  src/ui/extras.py
  src/ui/footer.py
  src/ui/header.py
  src/ui/inputs.py
  src/ui/layouts.py
  src/ui/styles.py
  src/utils.py
Labels: enhancement

#14 Release v0.4.1
  src/files/faq.md
  src/ui/footer.py
Labels: documentation

#15 Release v0.5.0
  app.py
  src/callbacks.py
  src/database.py
  src/entities.py
  src/files/announcements.yml
  src/ui/__init__.py
  src/ui/accordions.py
  src/ui/buttons.py
  src/ui/drawer.py
  src/ui/header.py
  src/ui/inputs.py
  src/ui/layouts.py
  src/ui/modals.py
  src/ui/tables.py
  src/utils.py
Labels: enhancement

#16 Release v0.5.1
  src/callbacks.py
  src/database.py
  src/ui/footer.py
  src/ui/modals.py
Labels: bug

#17 Release v0.5.2
  src/database.py
  src/ui/extras.py
  src/ui/footer.py
  src/utils.py
Labels: bug

#18 Release v0.5.3
  src/database.py
  src/ui/footer.py
Labels: bug

#19 Release v0.5.4
  src/callbacks.py
  src/database.py
  src/files/announcements.yml
  src/ui/accordions.py
  src/ui/footer.py
  src/ui/inputs.py
Labels: bug
